### ISSUE TITLE
Broken ELINA after 9c99c4d177c691f98f2031657c18fe6fbe4c7571

### ISSUE THREAD

**Issue by Holt59** [eth-sri/ELINA#59]
I am trying to use ERAN and thus I need to build ELINA to use it. I followed the instruction in the ERAN README to the letter. The build went ok, but as soon as I try to run the `python3` command at the end, I get the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 7, in <module>
    from eran import ERAN
  File "./eran.py", line 7, in <module>
    from optimizer import *
  File "./optimizer.py", line 4, in <module>
    from deepzono_nodes import *
  File "./deepzono_nodes.py", line 15, in <module>
    from refine_activation import *
  File "./refine_activation.py", line 9, in <module>
    from krelu import encode_kactivation_cons
  File "./krelu.py", line 5, in <module>
    from fppoly import *
  File "../ELINA/python_interface/fppoly.py", line 22, in <module>
    from fppoly_imports import *
  File "../ELINA/python_interface/fppoly_imports.py", line 25, in <module>
    fppoly_api = CDLL("libfppoly.so")
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/libfppoly.so: undefined symbol: omp_get_num_procs
```

This seems to come from some recent changes, in particular https://github.com/eth-sri/ELINA/commit/9c99c4d177c691f98f2031657c18fe6fbe4c7571

Unfortunately, none of the instructions mention OpenMP or anything similar. I tried installing various `libomp-dev` version but nothing worked.

**Comment by anianruoss** [comment]
Hi @Holt59, sorry about that. This should be fixed now. Feel free to reopen if the problem persists.
